### PR TITLE
Ignore more proxy headers

### PR DESCRIPTION
**Pull request by dochang**
tkf#30

### CODE REVIEW

**Comment by abingham** [comment]
Thanks!

**Comment by dochang** [comment]
@abingham Thank you for adopting `request`. I saw you have migrated the recipe in melpa. But `request-deferred` recipe also needs to be migrated.  Also, I suggest you migrate the recipe in el-get too.

**Comment by abingham** [comment]
Honestly I'm trying to make as few changes as possible. I eventually want @tkf to take it back over. Is there a strong technical reason to migrate `request-deferred` right now?

And good point about el-get. I've [suggested that they update their recipe](https://github.com/dimitri/el-get/issues/2314).

**Comment by abingham** [comment]
Ah, wait, I see what you're saying about request-deferred...I had forgotten that it's part of the same repo! I'll update the melpa recipe. Thanks.

**Comment by abingham** [comment]
I've submitted a [PR to melpa](https://github.com/milkypostman/melpa/pull/3473) redirecting request-deferred to this repo.

**Pull request merged**
